### ISSUE TITLE
custom.yaml

### ISSUE THREAD

**Issue by pavophilip** [brettch/bedrock-server#1]
How i can provide and apply custom.yaml for mods?

**Comment by brettch** [comment]
Good question :-)  I haven't been using a custom.yaml.  I'll take a look, hopefully just a matter of adding another symlink.

**Comment by brettch** [comment]
You should be able to add a custom.yaml file to your configuration directory now as well.

I've pushed new images to dockerhub: https://hub.docker.com/r/bretth/bedrock-server

Let me know if you encounter any issues.
